package limite;

import Model.Imovel;
import Model.Util;
import controle.ControlePrincipal;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;

public class CatalogoImoveis extends javax.swing.JFrame {

    ControlePrincipal ctrPrincipal;

    ArrayList<Imovel> imoveis = new ArrayList<Imovel>();

    public CatalogoImoveis(ControlePrincipal ctrPrincipal) {
        this.ctrPrincipal = ctrPrincipal;
        initComponents();
    }

    public void showCatalogo() {
        cbTipo.removeAllItems();
        cbTipo.addItem(Util.LOTE);
        cbTipo.addItem(Util.CASA);
        cbTipo.addItem(Util.APTO);
        cbTipo.addItem(Util.SALA);
        cbTipo.addItem(Util.RURAL);

        listaImoveis.clearSelection();
        btAgenda.setEnabled(false);
        btProposta.setEnabled(false);

        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setVisible(true);
    }

    private void atualizaExibidor(Imovel imovel) {
        this.infoImovel.setText("Codigo: " + imovel.getCodigo()
                + "\nPreço: " + imovel.getPreco()
                + "\nDescrição: " + imovel.getDescricao());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaImoveis = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        cbTipo = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        imovelImage = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoImovel = new javax.swing.JTextArea();
        btAgenda = new javax.swing.JButton();
        btProposta = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CATALOGO DE IMÓVEIS");

        listaImoveis.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaImoveis.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaImoveis.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listaImoveis.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaImoveisValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaImoveis);

        jLabel2.setText("Tipo de Imóvel:");

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        imovelImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imovelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/placeholder.jpg"))); // NOI18N
        imovelImage.setText("jLabel3");
        imovelImage.setMaximumSize(new java.awt.Dimension(200, 200));
        imovelImage.setMinimumSize(new java.awt.Dimension(200, 200));

        infoImovel.setColumns(20);
        infoImovel.setLineWrap(true);
        infoImovel.setRows(5);
        jScrollPane2.setViewportView(infoImovel);

        btAgenda.setText("Agendar Visita");
        btAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAgendaActionPerformed(evt);
            }
        });

        btProposta.setText("Fazer Proposta");
        btProposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPropostaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btAgenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btProposta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(imovelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(imovelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btAgenda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btProposta)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel4.setText("Lista de Imovéis:");

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addComponent(cbTipo, 0, 185, Short.MAX_VALUE)
                        .addComponent(jScrollPane1))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAgendaActionPerformed
        if (listaImoveis.getSelectedIndex() == -1) {
            return;
        }
        this.ctrPrincipal.ctrVisita.lmtVisita.cadastraVisita(
                Integer.parseInt(
                        listaImoveis.getSelectedValue()
                )
        );
    }//GEN-LAST:event_btAgendaActionPerformed

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        this.listaImoveis.clearSelection();
        this.infoImovel.setText("");

        this.imoveis = this.ctrPrincipal.ctrImovel.getByTipo(
                (String) cbTipo.getSelectedItem());
        DefaultListModel lista = new DefaultListModel();

        this.listaImoveis.removeAll();

        for (Imovel i : this.imoveis) {
            if (i.getEstado().equals(Util.ATIVO)) {
                lista.addElement(String.valueOf(i.getCodigo()));
            }
        }

        this.listaImoveis.setModel(lista);
    }//GEN-LAST:event_cbTipoActionPerformed

    private void listaImoveisValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaImoveisValueChanged
        if (listaImoveis.getSelectedIndex() > -1) {
            Imovel i = this.ctrPrincipal.ctrImovel.getByCodigo(
                    Integer.parseInt(listaImoveis.getSelectedValue()));
            btAgenda.setEnabled(true);
            btProposta.setEnabled(true);
            atualizaExibidor(i);
            
            File f = new File(i.getArquivoFoto());
            if (f.exists()) {
                imovelImage.setIcon(new ImageIcon(i.getArquivoFoto()));
            }
        } else {
            btAgenda.setEnabled(false);
            btProposta.setEnabled(false);
        }
    }//GEN-LAST:event_listaImoveisValueChanged

    private void btPropostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPropostaActionPerformed
        if (listaImoveis.getSelectedIndex() == -1) {
            return;
        }

        System.out.println(listaImoveis.getSelectedIndex());

        this.ctrPrincipal.ctrProposta.lmtProposta.cadastraProposta(
                Integer.parseInt(
                        listaImoveis.getSelectedValue()
                )
        );
    }//GEN-LAST:event_btPropostaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgenda;
    private javax.swing.JButton btProposta;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel imovelImage;
    private javax.swing.JTextArea infoImovel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JList<String> listaImoveis;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
