/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package limite;

import controle.ControlePrincipal;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.Action;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Model.Corretor;
import Model.CorretorComissionado;
import Model.CorretorContratado;
import Model.Venda;

/**
 *
 * @author Ruan
 */
public class RelatorioFaturamento extends javax.swing.JFrame {

    /**
     * Creates new form RelatorioFaturamento
     */
    ControlePrincipal ctrPrincipal;

    public RelatorioFaturamento(ControlePrincipal ctrPrincipal) {
        initComponents();

        this.ctrPrincipal = ctrPrincipal;

        cbAno.removeAllItems();
        cbMes.removeAllItems();

        ArrayList<String> anosDisponiveis = new ArrayList<String>();

        for (Venda v : ctrPrincipal.ctrVenda.getListaVendas()) {
            int ano = v.getDataVenda().get(Calendar.YEAR);
            if (!anosDisponiveis.contains(String.valueOf(ano))) {
                anosDisponiveis.add(String.valueOf(ano));
            }
        }

        if (anosDisponiveis.size() != 0) {
            for (int i = 0; i < anosDisponiveis.size(); i++) {
                cbAno.addItem(anosDisponiveis.get(i));
            }
        } else {
            cbAno.addItem("--");
            cbMes.addItem("--");
            JOptionPane.showMessageDialog(null, "Não há vendas cadastradas no sistema!", "Error", JOptionPane.ERROR_MESSAGE);
        }

        this.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbAno = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbMes = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Escolha uma data para gerar o relatiorio:");

        jLabel2.setText("Ano:");

        cbAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAnoActionPerformed(evt);
            }
        });

        jLabel3.setText("Mes:");

        cbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMesActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbAno, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAnoActionPerformed
        cbMes.removeAllItems();
        ArrayList<String> meses = new ArrayList<String>();

        for (Venda v : ctrPrincipal.ctrVenda.getListaVendas()) {
            if (String.valueOf(cbAno.getSelectedItem()).equals(String.valueOf(v.getDataVenda().get(Calendar.YEAR)))) {
                if (!meses.contains(String.valueOf(v.getDataVenda().get(Calendar.MONTH)))) {
                    meses.add(String.valueOf(v.getDataVenda().get(Calendar.MONTH)));
                }
            }
        }

        for (int i = 0; i < meses.size(); i++) {
            cbMes.addItem(meses.get(i));
        }
    }//GEN-LAST:event_cbAnoActionPerformed

    private void cbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMesActionPerformed
        String output = "";

        double fatTotal = 0;
        double gastos = 0;
        double lucro = 0;
        double salariosFixos = 0;
        
        for(Corretor c : ctrPrincipal.ctrCorretor.getLista()){
            if(c instanceof CorretorContratado){
                CorretorContratado aux = (CorretorContratado) c;
                salariosFixos += aux.getaSalarioFixo();
            }
        }
        
        for (Venda v : ctrPrincipal.ctrVenda.getListaVendas()) {
            if (String.valueOf(cbAno.getSelectedItem()).equals(String.valueOf(v.getDataVenda().get(Calendar.YEAR))) && String.valueOf(cbMes.getSelectedItem()).equals(String.valueOf(v.getDataVenda().get(Calendar.MONTH)))) {
                fatTotal += v.getValorNegociado() * 0.05;
                if (v.getCorretorResponsavel() instanceof CorretorComissionado) {
                    CorretorComissionado aux;
                    aux = (CorretorComissionado) v.getCorretorResponsavel();
                    gastos += (v.getValorNegociado() * 0.05) * (aux.getaComissao() / 100);
                } else {
                    CorretorContratado aux;
                    aux = (CorretorContratado) v.getCorretorResponsavel();
                    gastos += ((v.getValorNegociado()*0.05) * 0.01);
                }
            }
        }
        
        gastos += salariosFixos;
        lucro = fatTotal - gastos;

        textArea.setText("Faturamento Total da Imobiliaria: " + fatTotal
                + "\nLucro da Imobiliaria: " + lucro);
        
        textArea.setEditable(false);
    }//GEN-LAST:event_cbMesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbAno;
    private javax.swing.JComboBox<String> cbMes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
